# Generated by Django 4.0 on 2023-12-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='thread',
            name='first_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='second_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
