# Generated by Django 4.2.6 on 2023-11-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_measurement_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_value',
            new_name='hourly_average',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='measurement',
            name='end_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='start_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
