# Generated by Django 4.2.6 on 2023-11-26 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_measurement_value_measurement_hourly_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
