# Generated by Django 4.2.6 on 2023-11-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_measurement_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='device_id',
            field=models.IntegerField(),
        ),
    ]
