version: '3'
services:
  web:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/code
    networks:
      - my_network
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network: